# Generated by Django 2.2.16 on 2022-07-26 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Обязательное поле', verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Добавляетсяавтоматически при опубликовании', verbose_name='Дата создания комментария')),
                ('author', models.ForeignKey(help_text='Автор оставленного комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('post', models.ForeignKey(help_text='Комментарий к посту', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.Post', verbose_name='Комментарий')),
            ],
        ),
    ]
