# Generated by Django 2.2.16 on 2022-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Добавляетсяавтоматически при опубликовании', verbose_name='Дата создания поста'),
        ),
    ]
